<?php

namespace ContainerNZ87wrx;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getToDoControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EkpOiO7.App\Controller\ToDoController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EkpOiO7.App\\Controller\\ToDoController::delete()'] = ($container->privates['.service_locator.EkpOiO7'] ?? $container->load('get_ServiceLocator_EkpOiO7Service'))->withContext('App\\Controller\\ToDoController::delete()', $container);
    }
}
