<?php

namespace ContainerNZ87wrx;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getToDoControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.joMAzZM.App\Controller\ToDoController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.joMAzZM.App\\Controller\\ToDoController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'toDo' => ['privates', 'App\\Entity\\ToDo', 'getToDoService', true],
        ], [
            'toDo' => 'App\\Entity\\ToDo',
        ]))->withContext('App\\Controller\\ToDoController::show()', $container);
    }
}
