
services:
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
