<?php

namespace ContainerDZX1Uzi;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getToDoControllereditService extends App_KernelProductionDebugContainer
{
    /**
     * Gets the private '.service_locator.EkpOiO7.App\Controller\ToDoController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.EkpOiO7'] ?? $container->load('get_ServiceLocator_EkpOiO7Service'));

        if (isset($container->privates['.service_locator.EkpOiO7.App\\Controller\\ToDoController::edit()'])) {
            return $container->privates['.service_locator.EkpOiO7.App\\Controller\\ToDoController::edit()'];
        }

        return $container->privates['.service_locator.EkpOiO7.App\\Controller\\ToDoController::edit()'] = $a->withContext('App\\Controller\\ToDoController::edit()', $container);
    }
}
