<?php

namespace ContainerTlOEQ9g;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_S2xCz8DService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.s2xCz8D' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.s2xCz8D'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\ToDoController::index' => ['privates', '.service_locator.lx7OlN9.App\\Controller\\ToDoController::index()', 'getToDoControllerindexService', true],
            'App\\Controller\\ToDoController::new' => ['privates', '.service_locator.egipcEH.App\\Controller\\ToDoController::new()', 'getToDoControllernewService', true],
            'App\\Controller\\ToDoController::show' => ['privates', '.service_locator.joMAzZM.App\\Controller\\ToDoController::show()', 'getToDoControllershowService', true],
            'App\\Controller\\ToDoController::edit' => ['privates', '.service_locator.EkpOiO7.App\\Controller\\ToDoController::edit()', 'getToDoControllereditService', true],
            'App\\Controller\\ToDoController::delete' => ['privates', '.service_locator.EkpOiO7.App\\Controller\\ToDoController::delete()', 'getToDoControllerdeleteService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\ToDoController:index' => ['privates', '.service_locator.lx7OlN9.App\\Controller\\ToDoController::index()', 'getToDoControllerindexService', true],
            'App\\Controller\\ToDoController:new' => ['privates', '.service_locator.egipcEH.App\\Controller\\ToDoController::new()', 'getToDoControllernewService', true],
            'App\\Controller\\ToDoController:show' => ['privates', '.service_locator.joMAzZM.App\\Controller\\ToDoController::show()', 'getToDoControllershowService', true],
            'App\\Controller\\ToDoController:edit' => ['privates', '.service_locator.EkpOiO7.App\\Controller\\ToDoController::edit()', 'getToDoControllereditService', true],
            'App\\Controller\\ToDoController:delete' => ['privates', '.service_locator.EkpOiO7.App\\Controller\\ToDoController::delete()', 'getToDoControllerdeleteService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\ToDoController::index' => '?',
            'App\\Controller\\ToDoController::new' => '?',
            'App\\Controller\\ToDoController::show' => '?',
            'App\\Controller\\ToDoController::edit' => '?',
            'App\\Controller\\ToDoController::delete' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\ToDoController:index' => '?',
            'App\\Controller\\ToDoController:new' => '?',
            'App\\Controller\\ToDoController:show' => '?',
            'App\\Controller\\ToDoController:edit' => '?',
            'App\\Controller\\ToDoController:delete' => '?',
        ]);
    }
}
