<?php

namespace ContainerTlOEQ9g;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getToDoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Entity\ToDo' shared autowired service.
     *
     * @return \App\Entity\ToDo
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Entity/ToDo.php';

        return $container->privates['App\\Entity\\ToDo'] = new \App\Entity\ToDo();
    }
}
