<?php

namespace ContainerTlOEQ9g;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getToDoControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lx7OlN9.App\Controller\ToDoController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lx7OlN9.App\\Controller\\ToDoController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'toDoRepository' => ['privates', 'App\\Repository\\ToDoRepository', 'getToDoRepositoryService', true],
        ], [
            'toDoRepository' => 'App\\Repository\\ToDoRepository',
        ]))->withContext('App\\Controller\\ToDoController::index()', $container);
    }
}
