<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDZX1Uzi\App_KernelProductionDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDZX1Uzi/App_KernelProductionDebugContainer.php') {
    touch(__DIR__.'/ContainerDZX1Uzi.legacy');

    return;
}

if (!\class_exists(App_KernelProductionDebugContainer::class, false)) {
    \class_alias(\ContainerDZX1Uzi\App_KernelProductionDebugContainer::class, App_KernelProductionDebugContainer::class, false);
}

return new \ContainerDZX1Uzi\App_KernelProductionDebugContainer([
    'container.build_hash' => 'DZX1Uzi',
    'container.build_id' => '1a5be8c0',
    'container.build_time' => 1753040423,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDZX1Uzi');
