<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_to_do_index' => [[], ['_controller' => 'App\\Controller\\ToDoController::index'], [], [['text', '/to/do']], [], [], []],
    'app_to_do_new' => [[], ['_controller' => 'App\\Controller\\ToDoController::new'], [], [['text', '/to/do/new']], [], [], []],
    'app_to_do_show' => [['id'], ['_controller' => 'App\\Controller\\ToDoController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/to/do']], [], [], []],
    'app_to_do_edit' => [['id'], ['_controller' => 'App\\Controller\\ToDoController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/to/do']], [], [], []],
    'app_to_do_delete' => [['id'], ['_controller' => 'App\\Controller\\ToDoController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/to/do']], [], [], []],
    'App\Controller\ToDoController::index' => [[], ['_controller' => 'App\\Controller\\ToDoController::index'], [], [['text', '/to/do']], [], [], []],
    'App\Controller\ToDoController::new' => [[], ['_controller' => 'App\\Controller\\ToDoController::new'], [], [['text', '/to/do/new']], [], [], []],
    'App\Controller\ToDoController::show' => [['id'], ['_controller' => 'App\\Controller\\ToDoController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/to/do']], [], [], []],
    'App\Controller\ToDoController::edit' => [['id'], ['_controller' => 'App\\Controller\\ToDoController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/to/do']], [], [], []],
    'App\Controller\ToDoController::delete' => [['id'], ['_controller' => 'App\\Controller\\ToDoController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/to/do']], [], [], []],
];
