<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNZ87wrx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNZ87wrx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNZ87wrx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNZ87wrx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNZ87wrx\App_KernelDevDebugContainer([
    'container.build_hash' => 'NZ87wrx',
    'container.build_id' => '9008f3cb',
    'container.build_time' => 1753038371,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNZ87wrx');
